#index:
#    path: /
#    controller: App\Controller\DefaultController::index

usuarios:
  path: /usuarios
  controller: App\Controller\UsuariosController::usuarios
  methods: GET, POST

usuario:
  path: /usuario/{id}
  controller: App\Controller\UsuariosController::usuario
  methods: GET, PUT, DELETE

seguidos_usuario:
  path: /usuario/{id}/seguidos
  controller: App\Controller\UsuariosController::seguidosUsuario
  methods: GET

seguir_usuario:
  path: /usuario/{id}/sigue/{usuario_seguido_id}
  controller: App\Controller\UsuariosController::seguirUsuario
  methods: POST, DELETE

configuraciones_usuario:
  path: /configuracion/{id}/configuracion
  controller: App\Controller\ConfiguracionController::configuracionUsuario
  methods: GET, PUT

podcasts:
  path: /podcasts
  controller: App\Controller\PodcastController::podcasts
  methods: GET, POST

podcast:
  path: /podcast/{id}
  controller: App\Controller\PodcastController::podcast
  methods: GET

podcasts_usuario:
  path: /usuario/{id}/podcasts
  controller: App\Controller\PodcastController::podcastsUsuario
  methods: GET

seguir_podcast:
  path: /usuario/{id}/podcast/{id}
  controller: App\Controller\PodcastController::seguirPodcast
  methods: POST, DELETE

capitulos:
  path: /podcast/{id}/capitulos
  controller: App\Controller\CapituloController::capitulosPodcast
  methods: GET

capitulo:
  path: /podcast/{id}/capitulo/{id}
  controller: App\Controller\CapituloController::capituloByIdAndPodcastId
  methods: GET

suscripciones:
  path: /usuario/{id}/suscripciones
  controller: App\Controller\SuscripcionController::suscripcionesUsuario
  methods: GET

suscripcion:
  path: /usuario/{id}/suscripcion/{id}
  controller: App\Controller\SuscripcionController::suscripcionByIdAndUsuarioId
  methods: GET

playlists:
  path: /playlists
  controller: App\Controller\PlaylistController::playlists
  methods: GET, POST

playlist:
  path: /playlist/{id}
  controller: App\Controller\PlaylistController::playlist
  methods: GET

playlists_usuario:
  path: /usuario/{id}/playlists
  controller: App\Controller\PlaylistController::playlistsUsuario
  methods: GET

playlist_usuario:
  path: /usuario/{id}/playlist/{id}
  controller: App\Controller\PlaylistController::playlistByIdAndUsuarioId
  methods: GET, PUT, DELETE

canciones:
  path: /canciones
  controller: App\Controller\CancionController::canciones
  methods: GET

cancion:
  path: /cancion/{id}
  controller: App\Controller\CancionController::cancion
  methods: GET

canciones_playlist:
  path: /playlist/{id}/canciones
  controller: App\Controller\CancionController::cancionesPlaylist
  methods: GET

anadir_cancion_playlist:
  path: /playlist/{id}/cancion/{id}
  controller: App\Controller\CancionController::anadirCancionToPlaylist
  methods: POST, DELETE

artistas:
  path: /artistas
  controller: App\Controller\ArtistaController::artistas
  methods: GET

albums_artista:
  path: /artista/{id}/albums
  controller: App\Controller\ArtistaController::albumsArtista
  methods: GET

album_artista:
  path: /artista/{id}/album/{id}
  controller: App\Controller\ArtistaController::albumByIdAndArtistaId
  methods: GET

albums:
  path: /albums
  controller: App\Controller\AlbumController::albums
  methods: GET

album:
  path: /album/{id}
  controller: App\Controller\AlbumController::album
  methods: GET

canciones_album:
  path: /album/{id}/canciones
  controller: App\Controller\CancionController::cancionesAlbum
  methods: GET

calidades:
  path: /calidades
  controller: App\Controller\CalidadController::calidades
  methods: GET

idiomas:
  path: /idioma
  controller: App\Controller\IdiomaController::idioma
  methods: GET

tipos_desarga:
  path: /tipo_descarga
  controller: App\Controller\TipoDescargaController::tiposDescarga
  methods: GET
